---
- name: Deploy Apache Docker Container
  hosts: local_hosts
  become: true
  tasks:
    - name: Pull Apache Docker image
      docker_image:
        name: httpd
        state: present

    - name: Run Apache Docker container
      docker_container:
        name: apache_container
        image: httpd
        state: started
        ports:
          - "8080"
